services:
  scrc_ms_asignar_priorizacion:
    build: .
    container_name: scrc_ms_asignar_priorizacion
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scrc_ms_asignar_priorizacion.rule=Host(`APP_TRAEFIK_HOST`)"
      - "traefik.http.routers.scrc_ms_asignar_priorizacion.entrypoints=websecure"
      - "traefik.http.routers.scrc_ms_asignar_priorizacion.tls.certresolver=letsencrypt"
      - "traefik.http.services.scrc_ms_asignar_priorizacion.loadbalancer.server.port=8000"
    env_file:
      - .env
    networks:
      - share_network

networks:
  share_network:
    external: true
